version: '3'
services: 
  app:
    build: ./php
    ports:
      - '8000:80'
    volumes: 
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    ports:
       - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dev-user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: bbs
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
