CREATE TABLE IF NOT EXISTS `user` (
    `id` INT AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `password` VARCHAR(50) NOT NULL,
    `created_at` Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `post` (
    `id` INT AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `text` TEXT NOT NULL,
    `created_at` Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);
