CREATE TABLE IF NOT EXISTS `users` (
    `id` INT  AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `created_at` Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE (`email`)
);

CREATE TABLE IF NOT EXISTS `posts` (
    `id` INT AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `text` TEXT NOT NULL,
    `created_at` Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);
